# -*- coding: utf-8 -*-
"""제씨 한국 돌파 스크린.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14WJ3JM-reH-5lk9ypw-PXnZXPe9gVRCa
"""

# ============================================================
# 제씨식 돌파 스크리너 + 포지션 사이징 (단일 통합본)
# Colab 전용 / KOSPI / KOSDAQ
# ============================================================

# 0. 라이브러리 설치


import pandas as pd
import FinanceDataReader as fdr
from datetime import datetime
from concurrent.futures import ThreadPoolExecutor, as_completed


# ============================================================
# ⚙️ 계좌 설정 (여기만 네 상황에 맞게 수정)
# ============================================================
PEAK_BALANCE = 100_000_000      # 계좌 최고치 (예: 1억)
CURRENT_BALANCE = 92_000_000    # 현재 잔고 (참고용)
RISK_PCT = 0.5                  # 한 트레이드 리스크 % (공포장 기준 0.5%)

# ============================================================
# 1. 포지션 사이징 계산기
# ============================================================
def position_sizing(entry_price, stop_price):
    risk_amount = PEAK_BALANCE * (RISK_PCT / 100)
    per_share_risk = abs(entry_price - stop_price)

    if per_share_risk <= 0:
        return 0, 0, 0

    qty = int(risk_amount / per_share_risk)
    invested = int(qty * entry_price)
    max_loss = int(qty * per_share_risk)

    return qty, invested, max_loss

# ============================================================
# 2. 단일 종목 분석 (스크리닝 + 사이징)
# ============================================================
def analyze_stock(code, name):
    try:
        df = fdr.DataReader(code).tail(120)
        if len(df) < 100:
            return None

        price = df['Close'].iloc[-1]
        if price < 1000:
            return None

        # 거래대금
        avg_turnover = (df['Close'] * df['Volume']).tail(20).mean()
        if avg_turnover < 1_000_000_000:
            return None

        # EMA 정배열
        ema20 = df['Close'].ewm(span=20).mean().iloc[-1]
        ema50 = df['Close'].ewm(span=50).mean().iloc[-1]
        ema100 = df['Close'].ewm(span=100).mean().iloc[-1]
        if not (ema20 > ema50 > ema100):
            return None

        # ATR
        tr = pd.concat([
            df['High'] - df['Low'],
            abs(df['High'] - df['Close'].shift()),
            abs(df['Low'] - df['Close'].shift())
        ], axis=1).max(axis=1)
        atr = tr.rolling(14).mean().iloc[-1]
        atr_pct = atr / price * 100
        if atr_pct < 3:
            return None

        # 상대 거래량
        avg_vol = df['Volume'].tail(20).mean()
        rel_vol = df['Volume'].iloc[-1] / avg_vol
        if rel_vol < 1.5:
            return None

        # 돌파 조건
        recent_high = df['High'].tail(60).max()
        if price < recent_high * 0.98:
            return None

        # 손절가 (구조 + 변동성)
        stop_loss = max(price - 2 * atr, ema20)

        # 포지션 사이징
        qty, invested, max_loss = position_sizing(price, stop_loss)
        if qty <= 0:
            return None

        breakout_type = "신고가" if price >= recent_high else "고점근접"

        return {
            "Date": datetime.now().strftime("%Y-%m-%d"),
            "Code": code,
            "Name": name,
            "Price": int(price),
            "StopLoss": int(stop_loss),
            "Quantity": qty,
            "Invested": invested,
            "MaxLoss": max_loss,
            "RelVolume": round(rel_vol, 2),
            "ATR%": round(atr_pct, 2),
            "AvgTurnover": int(avg_turnover),
            "BreakoutType": breakout_type
        }

    except:
        return None

# ============================================================
# 3. 메인 실행
# ============================================================
def main():
    print("=== 돌파 스크리너 + 포지션 사이징 (자동 모드) ===")
    
    # 1. 코스피와 코스닥 종목 리스트를 한 번에 가져오기
    print("KOSPI와 KOSDAQ 종목을 모두 가져옵니다...")
    kospi = fdr.StockListing('KOSPI')
    kosdaq = fdr.StockListing('KOSDAQ')
    
    # 두 리스트를 하나로 합칩니다.
    universe = pd.concat([kospi, kosdaq])
    
    tasks = [(row['Code'], row['Name']) for _, row in universe.iterrows()]
    results = []

    print(f"총 {len(tasks)}개 종목 분석 시작 (코스피 + 코스닥)")

    with ThreadPoolExecutor(max_workers=8) as executor:
        futures = [
            executor.submit(analyze_stock, code, name)
            for code, name in tasks
        ]
        
        # 분석 결과를 수집합니다.
        for future in futures:
            res = future.result()
            if res:
                results.append(res)

    # 결과 출력 및 저장 (이 아랫부분은 기존 코드와 동일하게 유지하세요)
    if results:
        df_res = pd.DataFrame(results)
        print(df_res)
    else:
        print("조건에 맞는 종목이 없습니다.")

if __name__ == "__main__":
    main()
